round-time: 300
min-players: 2
allow-bossbar: true

allow:
  overworld: true
  nether: true
  end: false

messages:
  start: "&aüü¢ Block Shuffle started!"
  win: "&6üèÜ {player} won the game!"
  fail: "&cYou failed this round!"

weight-categories:
  common-blocks: 10
  building-blocks: 8
  decorative: 7
  common-ores: 6
  nether-blocks: 5
  default: 5
  uncommon-ores: 4
  end-blocks: 3
  rare-ores: 2
  ultra-rare: 1

weights:
  # STONE: 10
  # DIRT: 9

difficulty:
  weight-reduction-per-round: 0.15

blacklist:
  - END_PORTAL_FRAME
  - SPAWNER
  - BARRIER
  - DEEPSLATE_EMERALD_ORE
  - ANCIENT_DEBRIS
  - LODESTONE
  - COMMAND_BLOCK
  - STRUCTURE_BLOCK
  - JIGSAW
  - ENCHANTING_TABLE
  - BEACON
  - DRAGON_EGG
  - NETHER_PORTAL
  - END_PORTAL
  - SOUL_CAMPFIRE
  - CAMPFIRE
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  - ARMOR_STAND
  - PAINTING
  - ENDER_DRAGON_HEAD
  - WITHER_SKELETON_SKULL
  - SKELETON_SKULL
  - ZOMBIE_HEAD
  - CREEPER_HEAD
  - PLAYER_HEAD
  - DRAGON_HEAD
  - PIGLIN_HEAD
